version: "3.7"
services:
  extension:
    healthcheck:
      test: ["CMD","curl","-f", "http://172.17.0.1:${PORT}",]
      interval: 1s
      retries: 30
      start_period: 60s
    build: .
    container_name: ${CONTAINER_NAME}
    user: root
    entrypoint: sh command.sh
    volumes:
      - ./.next:/usr/src/app/.next
      - ./components:/usr/src/app/components
      - ./pages:/usr/src/app/pages
      - ./pulic:/usr/src/app/pulic
      - ./src:/usr/src/app/src
      - ./next.config.js:/usr/src/app/next.config.js
      - ./package.json:/usr/src/app/package.json
      - ./command.sh:/usr/src/app/command.sh
    ports:
      - ${PORT}:3000
    restart: unless-stopped
    # cpus: .10
    # mem_limit: "512M"