version: "3.7"
services:
  extension:
    healthcheck:
      test: ["CMD","curl","-f", "http://172.17.0.1:${PORT}",]
      interval: 1s
      retries: 30
      start_period: 60s
    build: 
      context: .
      dockerfile: deploy.dockerfile
    container_name: ${CONTAINER_NAME}
    user: root
    entrypoint: sh deploy_command.sh
    ports:
      - ${PORT}:3000
    restart: unless-stopped
    # cpus: .10
    # mem_limit: "512M"